# Minor modification from http://www.it20.info/2017/07/yelb-yet-another-sample-app/ to demo CN-FW Palo Alto Networks
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
    tier: cache
  namespace: yelb-protected
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-db
  labels:
    app: yelb-db
    tier: backenddb
  namespace: yelb-protected
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: yelb-db
    tier: backenddb
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  labels:
    app: yelb-appserver
    tier: middletier
  namespace: yelb-protected
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: yelb-appserver
    tier: middletier
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
  namespace: yelb-protected
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: yelb-ui
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    paloaltonetworks.com/firewall: pan-fw
    k8s.v1.cni.cncf.io/networks: pan-cni
  name: yelb-ui-1ns
  namespace: yelb-protected
spec:
  replicas: 3
  selector:
   matchLabels:
    app: yelb-ui
  template:
    metadata:
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
      - name: yelb-ui-1ns
        image: melamin/yelb-ui-os:v1.7
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    paloaltonetworks.com/firewall: pan-fw
    k8s.v1.cni.cncf.io/networks: pan-cni
  name: redis-server-1ns
  namespace: yelb-protected
spec:
  replicas: 1
  selector:
   matchLabels:
    app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server-1ns
        image: centos/redis-32-centos7
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    paloaltonetworks.com/firewall: pan-fw
    k8s.v1.cni.cncf.io/networks: pan-cni
  name: yelb-db-1ns
  namespace: yelb-protected
spec:
  replicas: 1
  selector:
   matchLabels:
    app: yelb-db
  template:
    metadata:
      labels:
        app: yelb-db
        tier: backenddb
    spec:
      containers:
      - name: yelb-db-1ns
        image: melamin/yelb-db-os:v30
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    paloaltonetworks.com/firewall: pan-fw
    k8s.v1.cni.cncf.io/networks: pan-cni
  name: yelb-appserver-1ns
  namespace: yelb-protected
spec:
  replicas: 1
  selector:
   matchLabels:
    app: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
        tier: middletier
    spec:
      containers:
      - name: yelb-appserver-1ns
        image: melamin/yelb-appserver-os:v1.5
        ports:
        - containerPort: 4567
